spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
      connection:
        provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Use PostgreSQL dialect
  datasource:
    driver-class-name: org.postgresql.Driver # Use PostgreSQL driver
    url: ${DATABASE_URL} # Heroku provides the PostgreSQL URL
    username: ${DATABASE_USERNAME} # Heroku provides the username
    password: ${DATABASE_PASSWORD} # Heroku provides the password
    hikari:
      maximumPoolSize: 30
      connectionTimeout: 30000
      maxLifetime: 60000

server:
  port: ${PORT:8080} # Use the provided Heroku port or default to 8080

jwt:
  secret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
